language: bash
sudo: false
install: true
addons:
  apt:
    packages:
    - lua5.1
    - luarocks

before_install:
  - luarocks install --local lpeg
  - "`luarocks path`" # set PATH to include local tree

script:
  - find src -iname "*.lua" | xargs luac -p

notifications:
  email:
    on_success: never
    on_failure: change
